// Code generated by mockery v2.38.0. DO NOT EDIT.

package oidcmocks

import (
	mock "github.com/stretchr/testify/mock"

	zap "go.uber.org/zap"
)

// MockloggerInterface is an autogenerated mock type for the loggerInterface type
type MockloggerInterface struct {
	mock.Mock
}

type MockloggerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockloggerInterface) EXPECT() *MockloggerInterface_Expecter {
	return &MockloggerInterface_Expecter{mock: &_m.Mock}
}

// Debugw provides a mock function with given fields: message, keysAndValues
func (_m *MockloggerInterface) Debugw(message string, keysAndValues ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, keysAndValues...)
	_m.Called(_ca...)
}

// MockloggerInterface_Debugw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugw'
type MockloggerInterface_Debugw_Call struct {
	*mock.Call
}

// Debugw is a helper method to define mock.On call
//   - message string
//   - keysAndValues ...interface{}
func (_e *MockloggerInterface_Expecter) Debugw(message interface{}, keysAndValues ...interface{}) *MockloggerInterface_Debugw_Call {
	return &MockloggerInterface_Debugw_Call{Call: _e.mock.On("Debugw",
		append([]interface{}{message}, keysAndValues...)...)}
}

func (_c *MockloggerInterface_Debugw_Call) Run(run func(message string, keysAndValues ...interface{})) *MockloggerInterface_Debugw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockloggerInterface_Debugw_Call) Return() *MockloggerInterface_Debugw_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockloggerInterface_Debugw_Call) RunAndReturn(run func(string, ...interface{})) *MockloggerInterface_Debugw_Call {
	_c.Call.Return(run)
	return _c
}

// Errorw provides a mock function with given fields: message, keysAndValues
func (_m *MockloggerInterface) Errorw(message string, keysAndValues ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, keysAndValues...)
	_m.Called(_ca...)
}

// MockloggerInterface_Errorw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorw'
type MockloggerInterface_Errorw_Call struct {
	*mock.Call
}

// Errorw is a helper method to define mock.On call
//   - message string
//   - keysAndValues ...interface{}
func (_e *MockloggerInterface_Expecter) Errorw(message interface{}, keysAndValues ...interface{}) *MockloggerInterface_Errorw_Call {
	return &MockloggerInterface_Errorw_Call{Call: _e.mock.On("Errorw",
		append([]interface{}{message}, keysAndValues...)...)}
}

func (_c *MockloggerInterface_Errorw_Call) Run(run func(message string, keysAndValues ...interface{})) *MockloggerInterface_Errorw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockloggerInterface_Errorw_Call) Return() *MockloggerInterface_Errorw_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockloggerInterface_Errorw_Call) RunAndReturn(run func(string, ...interface{})) *MockloggerInterface_Errorw_Call {
	_c.Call.Return(run)
	return _c
}

// Infow provides a mock function with given fields: message, keysAndValues
func (_m *MockloggerInterface) Infow(message string, keysAndValues ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, keysAndValues...)
	_m.Called(_ca...)
}

// MockloggerInterface_Infow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infow'
type MockloggerInterface_Infow_Call struct {
	*mock.Call
}

// Infow is a helper method to define mock.On call
//   - message string
//   - keysAndValues ...interface{}
func (_e *MockloggerInterface_Expecter) Infow(message interface{}, keysAndValues ...interface{}) *MockloggerInterface_Infow_Call {
	return &MockloggerInterface_Infow_Call{Call: _e.mock.On("Infow",
		append([]interface{}{message}, keysAndValues...)...)}
}

func (_c *MockloggerInterface_Infow_Call) Run(run func(message string, keysAndValues ...interface{})) *MockloggerInterface_Infow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockloggerInterface_Infow_Call) Return() *MockloggerInterface_Infow_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockloggerInterface_Infow_Call) RunAndReturn(run func(string, ...interface{})) *MockloggerInterface_Infow_Call {
	_c.Call.Return(run)
	return _c
}

// Warnw provides a mock function with given fields: message, keysAndValues
func (_m *MockloggerInterface) Warnw(message string, keysAndValues ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, keysAndValues...)
	_m.Called(_ca...)
}

// MockloggerInterface_Warnw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnw'
type MockloggerInterface_Warnw_Call struct {
	*mock.Call
}

// Warnw is a helper method to define mock.On call
//   - message string
//   - keysAndValues ...interface{}
func (_e *MockloggerInterface_Expecter) Warnw(message interface{}, keysAndValues ...interface{}) *MockloggerInterface_Warnw_Call {
	return &MockloggerInterface_Warnw_Call{Call: _e.mock.On("Warnw",
		append([]interface{}{message}, keysAndValues...)...)}
}

func (_c *MockloggerInterface_Warnw_Call) Run(run func(message string, keysAndValues ...interface{})) *MockloggerInterface_Warnw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockloggerInterface_Warnw_Call) Return() *MockloggerInterface_Warnw_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockloggerInterface_Warnw_Call) RunAndReturn(run func(string, ...interface{})) *MockloggerInterface_Warnw_Call {
	_c.Call.Return(run)
	return _c
}

// With provides a mock function with given fields: args
func (_m *MockloggerInterface) With(args ...interface{}) *zap.SugaredLogger {
	var _ca []interface{}
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 *zap.SugaredLogger
	if rf, ok := ret.Get(0).(func(...interface{}) *zap.SugaredLogger); ok {
		r0 = rf(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zap.SugaredLogger)
		}
	}

	return r0
}

// MockloggerInterface_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type MockloggerInterface_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockloggerInterface_Expecter) With(args ...interface{}) *MockloggerInterface_With_Call {
	return &MockloggerInterface_With_Call{Call: _e.mock.On("With",
		append([]interface{}{}, args...)...)}
}

func (_c *MockloggerInterface_With_Call) Run(run func(args ...interface{})) *MockloggerInterface_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockloggerInterface_With_Call) Return(_a0 *zap.SugaredLogger) *MockloggerInterface_With_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockloggerInterface_With_Call) RunAndReturn(run func(...interface{}) *zap.SugaredLogger) *MockloggerInterface_With_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockloggerInterface creates a new instance of MockloggerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockloggerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockloggerInterface {
	mock := &MockloggerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
