// Code generated by mockery v2.46.3. DO NOT EDIT.

package oidcmocks

import (
	oidc "github.com/kyma-project/test-infra/pkg/oidc"
	mock "github.com/stretchr/testify/mock"
)

// MockClaimsInterface is an autogenerated mock type for the ClaimsInterface type
type MockClaimsInterface struct {
	mock.Mock
}

type MockClaimsInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClaimsInterface) EXPECT() *MockClaimsInterface_Expecter {
	return &MockClaimsInterface_Expecter{mock: &_m.Mock}
}

// validateExpectations provides a mock function with given fields: _a0
func (_m *MockClaimsInterface) validateExpectations(_a0 oidc.Issuer) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for validateExpectations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(oidc.Issuer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClaimsInterface_validateExpectations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'validateExpectations'
type MockClaimsInterface_validateExpectations_Call struct {
	*mock.Call
}

// validateExpectations is a helper method to define mock.On call
//   - _a0 oidc.Issuer
func (_e *MockClaimsInterface_Expecter) validateExpectations(_a0 interface{}) *MockClaimsInterface_validateExpectations_Call {
	return &MockClaimsInterface_validateExpectations_Call{Call: _e.mock.On("validateExpectations", _a0)}
}

func (_c *MockClaimsInterface_validateExpectations_Call) Run(run func(_a0 oidc.Issuer)) *MockClaimsInterface_validateExpectations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(oidc.Issuer))
	})
	return _c
}

func (_c *MockClaimsInterface_validateExpectations_Call) Return(_a0 error) *MockClaimsInterface_validateExpectations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClaimsInterface_validateExpectations_Call) RunAndReturn(run func(oidc.Issuer) error) *MockClaimsInterface_validateExpectations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClaimsInterface creates a new instance of MockClaimsInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaimsInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaimsInterface {
	mock := &MockClaimsInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
