// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// API is an autogenerated mock type for the API type
type API struct {
	mock.Mock
}

// CreateBucket provides a mock function with given fields: ctx, name, location
func (_m *API) CreateBucket(ctx context.Context, name string, location string) error {
	ret := _m.Called(ctx, name, location)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBucket provides a mock function with given fields: ctx, name
func (_m *API) DeleteBucket(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with given fields: ctx, bucket, storageObject
func (_m *API) Read(ctx context.Context, bucket string, storageObject string) ([]byte, error) {
	ret := _m.Called(ctx, bucket, storageObject)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = rf(ctx, bucket, storageObject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bucket, storageObject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Write provides a mock function with given fields: ctx, data, bucket, storageObject
func (_m *API) Write(ctx context.Context, data []byte, bucket string, storageObject string) error {
	ret := _m.Called(ctx, data, bucket, storageObject)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string) error); ok {
		r0 = rf(ctx, data, bucket, storageObject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
