// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/test-infra/prow/apis/prowjobs/v1"
)

// ReportClient is an autogenerated mock type for the ReportClient type
type ReportClient struct {
	mock.Mock
}

// GetName provides a mock function with given fields:
func (_m *ReportClient) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Report provides a mock function with given fields: pj
func (_m *ReportClient) Report(pj *v1.ProwJob) error {
	ret := _m.Called(pj)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.ProwJob) error); ok {
		r0 = rf(pj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShouldReport provides a mock function with given fields: pj
func (_m *ReportClient) ShouldReport(pj *v1.ProwJob) bool {
	ret := _m.Called(pj)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*v1.ProwJob) bool); ok {
		r0 = rf(pj)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
