#!/bin/bash
#
# The post-commit script runs all scripts from post-commit.d in specific order.
#

set -e
(
  cd "$(git rev-parse --show-toplevel)/.githooks/post-commit.d"
  shopt -s nullglob
  for hook in *.sh; do
      bash $hook
  done
  shopt -u nullglob
)

