#!/bin/bash
#
# The pre-commit script runs all scripts from pre-commit.d in specific order.
#

set -e
(
  cd "$(git rev-parse --show-toplevel)/.githooks/pre-commit.d"
  shopt -s nullglob
  for hook in *.sh; do
      bash $hook
  done
  shopt -u nullglob
)
