// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	mock "github.com/stretchr/testify/mock"
	cloudkms "google.golang.org/api/cloudkms/v1"
)

// Decryptor is an autogenerated mock type for the Decryptor type
type Decryptor struct {
	mock.Mock
}

// Decrypt provides a mock function with given fields: key, bytes
func (_m *Decryptor) Decrypt(key string, bytes []byte) (*cloudkms.DecryptResponse, error) {
	ret := _m.Called(key, bytes)

	var r0 *cloudkms.DecryptResponse
	if rf, ok := ret.Get(0).(func(string, []byte) *cloudkms.DecryptResponse); ok {
		r0 = rf(key, bytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudkms.DecryptResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = rf(key, bytes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
