// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// StorageReader is an autogenerated mock type for the StorageReader type
type StorageReader struct {
	mock.Mock
}

// Read provides a mock function with given fields: ctx, bucket, name
func (_m *StorageReader) Read(ctx context.Context, bucket string, name string) (io.Reader, error) {
	ret := _m.Called(ctx, bucket, name)

	var r0 io.Reader
	if rf, ok := ret.Get(0).(func(context.Context, string, string) io.Reader); ok {
		r0 = rf(ctx, bucket, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bucket, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
