name: kyma-project.io/tooling/test-infra-public
team: kyma/neighbors
images:
  - "alpine:3.24.1"
  - "europe-docker.pkg.dev/kyma-project/prod/dashboard-token-proxy:v20260610063021"
  - "europe-docker.pkg.dev/kyma-project/prod/github-webhook-gateway:v20260615052019"
  - "europe-docker.pkg.dev/kyma-project/prod/image-builder:v20260617065613"
  - "europe-docker.pkg.dev/kyma-project/prod/test-infra/rotate-service-account:v20260617065612"
  - "europe-docker.pkg.dev/kyma-project/prod/test-infra/service-account-keys-cleaner:v20260617065620"
  - "europe-docker.pkg.dev/kyma-project/prod/test-infra/signify-secret-rotator:v20260615052020"
  - "europe-docker.pkg.dev/kyma-project/prod/test-infra/slackmessagesender:v20260611052036"
  - "gcr.io/distroless/static:latest"
  - "golang:1.26.4-alpine3.22"
  - "python:3.14.6-alpine3.23"
