name: kyma-project.io/module/test-infra
team: kyma/Neighbors
images:
  - europe-docker.pkg.dev/kyma-project/prod/dashboard-token-proxy:v20260515102704
  - europe-docker.pkg.dev/kyma-project/prod/github-webhook-gateway:v20260515102706
  - europe-docker.pkg.dev/kyma-project/prod/test-infra/rotate-service-account:v20260515102710
  - europe-docker.pkg.dev/kyma-project/prod/test-infra/service-account-keys-cleaner:v20260518045212
  - europe-docker.pkg.dev/kyma-project/prod/test-infra/signify-secret-rotator:v20260512044756
  - europe-docker.pkg.dev/kyma-project/prod/test-infra/slackmessagesender:v20260512044756
