module-name: test-infra
kind: kyma
bdba:
    - europe-docker.pkg.dev/kyma-project/prod/dashboard-token-proxy:v20260515102704
    - europe-docker.pkg.dev/kyma-project/prod/github-webhook-gateway:v20260507212226
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/rotate-service-account:v20260507212222
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/service-account-keys-cleaner:v20260512092514
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/signify-secret-rotator:v20260512044756
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/slackmessagesender:v20260512044756
mend:
    language: golang-mod
    exclude:
        - '**/*_test.go'
checkmarx-one:
    preset: go-default
    exclude:
        - '**/*_test.go'
