module-name: test-infra
kind: kyma
bdba:
    - europe-docker.pkg.dev/kyma-project/prod/dashboard-token-proxy:v20260427060455
    - europe-docker.pkg.dev/kyma-project/prod/github-webhook-gateway:v20260427085621
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/rotate-service-account:v20260427060456
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/service-account-keys-cleaner:v20260427060455
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/signify-secret-rotator:v20260424221008
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/slackmessagesender:v20260408214034
mend:
    language: golang-mod
    exclude:
        - '**/*_test.go'
checkmarx-one:
    preset: go-default
    exclude:
        - '**/*_test.go'
