name: 'Install dependencies'
description: 'Install Node.js 20 and @actions/core'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: 24
    - run: |
        cd .github/actions/expose-jwt-action
        npm init -y
        npm install @actions/core@2.0.0
      shell: bash