name: 'Install dependencies'
description: 'Install Node.js 20 and @actions/core'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version: 24
    - run: |
        cd .github/actions/expose-jwt-action
        npm init -y
        npm install @actions/core@2.0.0
      shell: bash