// Code generated by mockery 2.9.0. DO NOT EDIT.

package automock

import (
	compute "google.golang.org/api/compute/v1"

	mock "github.com/stretchr/testify/mock"
)

// AddressAPI is an autogenerated mock type for the AddressAPI type
type AddressAPI struct {
	mock.Mock
}

// ListAddresses provides a mock function with given fields: project, region
func (_m *AddressAPI) ListAddresses(project string, region string) ([]*compute.Address, error) {
	ret := _m.Called(project, region)

	var r0 []*compute.Address
	if rf, ok := ret.Get(0).(func(string, string) []*compute.Address); ok {
		r0 = rf(project, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*compute.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(project, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveIP provides a mock function with given fields: project, region, name
func (_m *AddressAPI) RemoveIP(project string, region string, name string) error {
	ret := _m.Called(project, region, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(project, region, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
