// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import client "github.com/kyma-project/test-infra/development/tools/pkg/gcscleaner/storage"
import context "context"
import mock "github.com/stretchr/testify/mock"

// BucketHandle is an autogenerated mock type for the BucketHandle type
type BucketHandle struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx
func (_m *BucketHandle) Delete(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Object provides a mock function with given fields: name
func (_m *BucketHandle) Object(name string) client.ObjectHandle {
	ret := _m.Called(name)

	var r0 client.ObjectHandle
	if rf, ok := ret.Get(0).(func(string) client.ObjectHandle); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ObjectHandle)
		}
	}

	return r0
}

// Objects provides a mock function with given fields: ctx, q
func (_m *BucketHandle) Objects(ctx context.Context, q client.Query) client.ObjectIterator {
	ret := _m.Called(ctx, q)

	var r0 client.ObjectIterator
	if rf, ok := ret.Get(0).(func(context.Context, client.Query) client.ObjectIterator); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ObjectIterator)
		}
	}

	return r0
}
