// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import client "github.com/kyma-project/test-infra/development/tools/pkg/gcscleaner/storage"
import context "context"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Bucket provides a mock function with given fields: bucketName
func (_m *Client) Bucket(bucketName string) client.BucketHandle {
	ret := _m.Called(bucketName)

	var r0 client.BucketHandle
	if rf, ok := ret.Get(0).(func(string) client.BucketHandle); ok {
		r0 = rf(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.BucketHandle)
		}
	}

	return r0
}

// Buckets provides a mock function with given fields: ctx, projectID
func (_m *Client) Buckets(ctx context.Context, projectID string) client.BucketIterator {
	ret := _m.Called(ctx, projectID)

	var r0 client.BucketIterator
	if rf, ok := ret.Get(0).(func(context.Context, string) client.BucketIterator); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.BucketIterator)
		}
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *Client) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
