// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// ObjectAttrs is an autogenerated mock type for the ObjectAttrs type
type ObjectAttrs struct {
	mock.Mock
}

// Bucket provides a mock function with given fields:
func (_m *ObjectAttrs) Bucket() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// name provides a mock function with given fields:
func (_m *ObjectAttrs) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
