// Code generated by mockery v2.33.1. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// BucketAttrs is an autogenerated mock type for the BucketAttrs type
type BucketAttrs struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *BucketAttrs) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewBucketAttrs creates a new instance of BucketAttrs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBucketAttrs(t interface {
	mock.TestingT
	Cleanup(func())
}) *BucketAttrs {
	mock := &BucketAttrs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
