// Code generated by mockery v2.33.1. DO NOT EDIT.

package automock

import (
	"github.com/kyma-project/test-infra/pkg/tools/gcscleaner/storage"
	mock "github.com/stretchr/testify/mock"
)

// BucketIterator is an autogenerated mock type for the BucketIterator type
type BucketIterator struct {
	mock.Mock
}

// Next provides a mock function with given fields:
func (_m *BucketIterator) Next() (storage.BucketAttrs, error) {
	ret := _m.Called()

	var r0 storage.BucketAttrs
	var r1 error
	if rf, ok := ret.Get(0).(func() (storage.BucketAttrs, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() storage.BucketAttrs); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.BucketAttrs)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBucketIterator creates a new instance of BucketIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBucketIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *BucketIterator {
	mock := &BucketIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
