// Code generated by mockery v2.33.1. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// ObjectAttrs is an autogenerated mock type for the ObjectAttrs type
type ObjectAttrs struct {
	mock.Mock
}

// Bucket provides a mock function with given fields:
func (_m *ObjectAttrs) Bucket() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *ObjectAttrs) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewObjectAttrs creates a new instance of ObjectAttrs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewObjectAttrs(t interface {
	mock.TestingT
	Cleanup(func())
}) *ObjectAttrs {
	mock := &ObjectAttrs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
