// Code generated by mockery v2.33.1. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ObjectHandle is an autogenerated mock type for the ObjectHandle type
type ObjectHandle struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx
func (_m *ObjectHandle) Delete(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewObjectHandle creates a new instance of ObjectHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewObjectHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *ObjectHandle {
	mock := &ObjectHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
