// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ComputeAPI is an autogenerated mock type for the ComputeAPI type
type ComputeAPI struct {
	mock.Mock
}

// RemoveIP provides a mock function with given fields: ctx, project, region, name
func (_m *ComputeAPI) RemoveIP(ctx context.Context, project string, region string, name string) error {
	ret := _m.Called(ctx, project, region, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, project, region, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
