// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import compute "google.golang.org/api/compute/v1"
import mock "github.com/stretchr/testify/mock"

// NetworkAPI is an autogenerated mock type for the NetworkAPI type
type NetworkAPI struct {
	mock.Mock
}

// ListNetworks provides a mock function with given fields: project
func (_m *NetworkAPI) ListNetworks(project string) ([]*compute.Network, error) {
	ret := _m.Called(project)

	var r0 []*compute.Network
	if rf, ok := ret.Get(0).(func(string) []*compute.Network); ok {
		r0 = rf(project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*compute.Network)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveNetwork provides a mock function with given fields: project, name
func (_m *NetworkAPI) RemoveNetwork(project string, name string) error {
	ret := _m.Called(project, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(project, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
