// Code generated by mockery 2.9.0. DO NOT EDIT.

package automock

import (
	google "github.com/google/go-containerregistry/pkg/v1/google"
	mock "github.com/stretchr/testify/mock"
)

// ImageAPI is an autogenerated mock type for the ImageAPI type
type ImageAPI struct {
	mock.Mock
}

// DeleteImage provides a mock function with given fields: registry, repoName, digest, manifest
func (_m *ImageAPI) DeleteImage(registry string, repoName string, digest string, manifest google.ManifestInfo) error {
	ret := _m.Called(registry, repoName, digest, manifest)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, google.ManifestInfo) error); ok {
		r0 = rf(registry, repoName, digest, manifest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListImages provides a mock function with given fields: registry, repoName
func (_m *ImageAPI) ListImages(registry string, repoName string) (map[string]google.ManifestInfo, error) {
	ret := _m.Called(registry, repoName)

	var r0 map[string]google.ManifestInfo
	if rf, ok := ret.Get(0).(func(string, string) map[string]google.ManifestInfo); ok {
		r0 = rf(registry, repoName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]google.ManifestInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(registry, repoName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
