// Code generated by mockery v1.0.0. DO NOT EDIT.

package cluster

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAPI is an autogenerated mock type for the API type
type MockAPI struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, clusterConfig
func (_m *MockAPI) Create(ctx context.Context, clusterConfig Cluster) error {
	ret := _m.Called(ctx, clusterConfig)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Cluster) error); ok {
		r0 = rf(ctx, clusterConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, name, zoneID
func (_m *MockAPI) Delete(ctx context.Context, name string, zoneID string) error {
	ret := _m.Called(ctx, name, zoneID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, zoneID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
