{
 "title": "Pull Requests statistics",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center\"> Kyma-project pull requests statistics </h1>\n<p style=\"text-align:center\"> all data presented include DRAFT pull requests </p>\n\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "PR processing time (monthly average)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, avg(processing_time) as suma \nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        number,\n        labels_unpacked.name as label,\n        created_at,\n        closed_at\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`, UNNEST(labels) as labels_unpacked\n    WHERE pull_request.url != \"NULL\" AND closed_at IS NOT NULL\n  )\n)\nSELECT created_at as Time2, FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, TIMESTAMP_DIFF(closed_at, created_at, day) as processing_time from pulls \n\n)\ngroup by Time order by Time desc"
    }
   ]
  },
  {
   "title": "Total PR count",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as testinfra\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"test-infra\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as busola\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"busola\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as kyma\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"kyma\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as console\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"console\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as website\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"website\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as control_plane\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"control-plane\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as istio\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"istio\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as lifecycle_manager\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"lifecycle-manager\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as module_manager\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"module-manager\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as btp_manager\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"btp-manager\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as template_operator\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"template-operator\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as serverless_manager\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"serverless\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as warden\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"warden\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as examples\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"examples\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as keda_manager\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"keda-manager\") AND pull_request.url != \"NULL\"\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    }
   ]
  },
  {
   "title": "Currently open PRs",
   "type": "table",
   "gridPos": { "h": 19, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT Repository, count(repository) as Open_PRs_count\nFROM (WITH pulls AS\n(\n  (\n   SELECT  \n        repository.name as repository,\n        created_at, pull_request.url as url\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE pull_request.url != \"NULL\" and closed_at is NULL\n  )\n)\nSELECT created_at, repository, url from pulls\n\n)\ngroup by repository\norder by Repository asc"
    }
   ]
  },
  {
   "title": "Currently opened PRs",
   "type": "table",
   "gridPos": { "h": 19, "w": 7, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT Repository, created_at as Created, url\nFROM (WITH pulls AS\n(\n  (\n   SELECT  \n        repository.name as repository,\n        created_at, pull_request.url as url\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE pull_request.url != \"NULL\" and closed_at is NULL\n  )\n)\nSELECT created_at, repository, url from pulls\n\n)\n\norder by Repository asc, Created desc"
    }
   ]
  },
  {
   "title": "Currently Open PRs count ",
   "type": "graph",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as test_infra\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"test-infra\") AND pull_request.url != \"NULL\" and closed_at is NULL\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as busola\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"busola\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as kyma\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"kyma\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as console1\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"console\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as api_gateway\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"api-gateway\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as website\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"website\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as control_plane\n\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"control-plane\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as istio\n\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"istio\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as lifecycle_manager\n\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"lifecycle-manager\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as cli\n\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"cli\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as module_manager\n\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"module-manager\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as btp_manager\n\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"btp-manager\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as template_operator\n\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"template-operator\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as serverless_manager\n\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"serverless\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as keda_manager\n\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"keda-manager\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as warden\n\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"warden\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as qa_cli\n\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"qa-cli\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "SELECT concat(year,\"-\",month) as Time, repository, count(repository) as examples\nFROM (WITH pulls AS\n(\n  (\n   SELECT DISTINCT \n        repository.name as repository,\n        created_at,\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`\n    WHERE repository.name IN (\"examples\") AND pull_request.url != \"NULL\" and closed_at is null\n  )\n)\nSELECT FORMAT_TIMESTAMP( \"%Y\", created_at, \"UTC\") as year, FORMAT_TIMESTAMP( \"%m\", created_at, \"UTC\") as month, created_at, repository from pulls\n\n)\ngroup by Time, repository\norder by Time desc"
    }
   ]
  }
 ]
}