{
 "title": "Quality dashboard PoC",
 "time": { "from": "now-1w/w", "to": "now-1w/w" },
 "panels": [
  {
   "title": "Total incidents",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        number,\n        labels_unpacked.name as label\n    FROM sap-kyma-prow.github_issues.issues_backlog, UNNEST(labels) as labels_unpacked\n    WHERE state = \"open\"\n)\nSELECT \n    current_timestamp() as time,\n    label as metric,\n    COUNT(*)\nFROM issues_filtered\nWHERE label LIKE \"%incident\"\nAND number IN (SELECT number FROM issues_filtered  WHERE label = \"bug\")\nGROUP BY label"
    }
   ]
  },
  {
   "title": "New incidents",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        number,\n        labels_unpacked.name as label\n    FROM sap-kyma-prow.github_issues.issues_backlog, UNNEST(labels) as labels_unpacked\n    WHERE created_at >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)\n)\nSELECT \n    label,\n    COUNT(*)\nFROM issues_filtered\nWHERE label LIKE \"%incident\"\nAND number IN (SELECT number FROM issues_filtered  WHERE label = \"bug\")\nGROUP BY label"
    }
   ]
  },
  {
   "title": "Total bugs open",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        repository.name as repository,\n        number,\n        labels_unpacked.name as label\n    FROM `sap-kyma-prow.github_issues.issues`, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"bug\" AND repository.name IN (\"kyma\", \"control-plane\") AND state = \"open\"\n)\nSELECT \n    repository,\n    COUNT(*) as `cnt`\nFROM issues_filtered\nGROUP BY repository\nORDER BY repository ASC"
    },
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        number,\n        labels_unpacked.name as label\n    FROM `sap-kyma-prow.github_issues.issues_backlog`, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"bug\" AND state = \"open\"\n)\nSELECT \n    \"SKR\" as repository,\n    COUNT(*) as `cnt`\nFROM issues_filtered"
    }
   ]
  },
  {
   "title": "Job success rate (sligthly better data)",
   "type": "table-old",
   "description": "I have no idea it this works properly, too few entries on friday",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH all_jobs AS\n(\n    SELECT\n        jsonPayload.job as job,\n        jsonPayload.to as state\n    FROM `sap-kyma-prow.prow_jobs.stderr`\n    WHERE\n        --TIMESTAMP BETWEEN \"2021-05-13\" AND \"2021-05-21\"\n        timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)\n        AND jsonPayload.type != \"presubmit\"\n        AND jsonPayload.to IN ( \"success\", \"error\", \"failure\")\n)\nSELECT \n    job,\n    COUNTIF(state = \"success\") as `cnt_success`,\n    COUNT(*) as `cnt`,\n    COUNTIF(state = \"success\") / COUNT(*) * 100 as `success`\nFROM all_jobs \nGROUP BY job\nORDER BY job"
    }
   ]
  },
  {
   "title": "Last result (test coveraga mockup)",
   "type": "gauge",
   "description": "To simulate how test coverage could look like",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH JOBS as (\nSELECT\n      MIN(CAST(REGEXP_EXTRACT(textPayload, r\"(\\d+\\.\\d+)\") AS float64)) AS val\n    , ANY_VALUE(labels.k8s_pod_prow_k8s_io_job) AS k8s_pod_prow_k8s_io_job\n    , MIN(timestamp) as timestamp\n  FROM `sap-kyma-prow.total_test_coverage.stdout`\n  GROUP BY resource.labels.pod_name\n  HAVING k8s_pod_prow_k8s_io_job NOT LIKE \"pre-%\"\n)\nSELECT a.k8s_pod_prow_k8s_io_job\n     , b.last_result\n     , b.last_timestamp\n     , a.samples_cnt\n     , a.min_result\n     , a.max_result\n     , ROUND(COALESCE((b.last_result - b.previous_result), 0),2) AS last_change\n     , format(\"https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/%s\", a.k8s_pod_prow_k8s_io_job)  as link\n     , a.stddev\n from \n( SELECT\n    k8s_pod_prow_k8s_io_job\n  , MIN(val) AS min_result\n  , MAX(val) AS max_result\n  , AVG(val) AS avg \n  , COUNT(*) AS samples_cnt\n  , MAX(timestamp) AS timestamp\n  , STDDEV_POP(val) AS stddev\nFROM JOBS\nGROUP BY k8s_pod_prow_k8s_io_job\nORDER BY k8s_pod_prow_k8s_io_job\n) a \nJOIN (SELECT \n   distinct(k8s_pod_prow_k8s_io_job) \n , FIRST_VALUE(val) OVER w1 AS last_result\n , FIRST_VALUE(timestamp) OVER w1 AS last_timestamp\n , NTH_VALUE(val,2) OVER w1 AS previous_result\nFROM JOBS\n WINDOW w1 AS (\n    PARTITION BY k8s_pod_prow_k8s_io_job ORDER BY timestamp DESC\n    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)\n) b on a.k8s_pod_prow_k8s_io_job = b.k8s_pod_prow_k8s_io_job"
    }
   ]
  },
  {
   "title": "Open bug age",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH bugs AS\n(\n    SELECT DISTINCT \n        repository.name as repository,\n        number,\n        labels_unpacked.name as label,\n        created_at\n    FROM `sap-kyma-prow.github_issues.issues`, UNNEST(labels) as labels_unpacked\n    WHERE repository.name  IN (\"kyma\", \"control-plane\") AND labels_unpacked.name = \"bug\" AND state = \"open\"\n)\nSELECT \n    (\n        SELECT \n            COUNT(*)\n        FROM bugs \n        WHERE created_at >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)\n    ) as one_week,\n    (\n        SELECT \n            COUNT(*)\n        FROM bugs \n        WHERE created_at <= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY)\n    ) as one_month,\n    (\n        SELECT \n            COUNT(*)\n        FROM bugs \n        WHERE created_at <= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30* 3 DAY)\n    ) as three_months,\n    (\n        SELECT \n            COUNT(*)\n        FROM bugs \n        WHERE created_at <= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30*6 DAY)\n    ) as six_months,"
    },
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH bugs AS\n(\n    SELECT DISTINCT \n        number,\n        labels_unpacked.name as label,\n        created_at\n    FROM `sap-kyma-prow.github_issues.issues_backlog`, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"bug\" AND state = \"open\"\n)\nSELECT \n    (\n        SELECT \n            COUNT(*)\n        FROM bugs \n        WHERE created_at >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)\n    ) as one_week,\n    (\n        SELECT \n            COUNT(*)\n        FROM bugs \n        WHERE created_at <= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY)\n    ) as one_month,\n    (\n        SELECT \n            COUNT(*)\n        FROM bugs \n        WHERE created_at <= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30* 3 DAY)\n    ) as three_months,\n    (\n        SELECT \n            COUNT(*)\n        FROM bugs \n        WHERE created_at <= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30*6 DAY)\n    ) as six_months,"
    }
   ]
  },
  {
   "title": "Test cases for release",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        repository.name as repository,\n        number,\n        labels_unpacked.name as label\n    FROM `sap-kyma-prow.github_issues.issues`, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"test-case\" AND state = \"open\"\n)\nSELECT \n    repository,\n    COUNT(*) as `cnt`\nFROM issues_filtered\nGROUP BY repository\nORDER BY repository"
    },
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        number,\n        labels_unpacked.name as label\n    FROM `sap-kyma-prow.github_issues.issues_backlog`, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"test-case\" AND state = \"open\"\n)\nSELECT\n    \"SKR\" as repository,\n    COUNT(*) as `cnt`\nFROM issues_filtered"
    }
   ]
  },
  {
   "title": "Open bugs per area",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        repository.name as repository,\n        number,\n        labels_unpacked.name as label\n    FROM `sap-kyma-prow.github_issues.issues`, UNNEST(labels) as labels_unpacked\n    WHERE repository.name IN (\"kyma\", \"control-plane\") AND state = \"open\"\n)\nSELECT \n    SUBSTR(label,6) as area,\n    COUNT(*) as `cnt`\nFROM issues_filtered\nWHERE label LIKE \"area/%\"\nAND number IN (SELECT number FROM issues_filtered WHERE label = \"bug\")\nGROUP BY label\nORDER BY area\n"
    },
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        number,\n        labels_unpacked.name as label\n    FROM `sap-kyma-prow.github_issues.issues_backlog`, UNNEST(labels) as labels_unpacked\n    WHERE state = \"open\"\n)\nSELECT \n    SUBSTR(label,6) as area,\n    COUNT(*) as `cnt`\nFROM issues_filtered\nWHERE label LIKE \"area/%\"\nAND number IN (SELECT number FROM issues_filtered WHERE label = \"bug\")\nGROUP BY label\nORDER BY area\n"
    }
   ]
  },
  {
   "title": "Critical issues",
   "type": "table",
   "description": "New counts all opened in the last 7 days",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        repository.name as repository,\n        number,\n        labels_unpacked.name as label,\n        created_at\n    FROM `sap-kyma-prow.github_issues.issues`, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"priority/critical\" AND state = \"open\"\n)\nSELECT\n    issues_all.repository,\n    critical_open,\n    COALESCE(critical_new, 0)\nFROM\n(\n    SELECT \n        repository,\n        COUNT(*) as `critical_open`\n    FROM issues_filtered\n    GROUP BY repository\n) AS issues_all LEFT JOIN (\n    SELECT \n        repository,\n        COUNT(*) as `critical_new`\n    FROM issues_filtered\n    WHERE created_at >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)\n    GROUP BY repository\n) AS issues_new ON issues_all.repository = issues_new.repository\n--GROUP BY repository\nORDER BY repository"
    },
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        number,\n        labels_unpacked.name as label,\n        created_at\n    FROM `sap-kyma-prow.github_issues.issues_backlog`, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"priority/critical\" AND state = \"open\"\n)\nSELECT\n    issues_all.repository,\n    critical_open,\n    COALESCE(critical_new, 0)\nFROM\n(\n    SELECT \n        \"SKR\" as repository,\n        COUNT(*) as `critical_open`\n    FROM issues_filtered\n    GROUP BY repository\n) AS issues_all LEFT JOIN (\n    SELECT \n        \"SKR\" as repository,\n        COUNT(*) as `critical_new`\n    FROM issues_filtered\n    WHERE created_at >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)\n    GROUP BY repository\n) AS issues_new ON issues_all.repository = issues_new.repository\n--GROUP BY repository\nORDER BY repository"
    }
   ]
  },
  {
   "title": "Provisioning success rate (mock data)",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deprovisioning success rate (mock data)",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 19 },
   "targets": [
    {}
   ]
  }
 ]
}