{
 "title": "Quality dashboard",
 "time": { "from": "now-1w/w", "to": "now-1w/w" },
 "panels": [
  {
   "title": "Job success rate",
   "type": "table-old",
   "gridPos": { "h": 27, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH all_jobs AS\n(\n    SELECT\n        jsonPayload.job as job,\n        jsonPayload.to as state,\n        timestamp\n    FROM `sap-kyma-prow.prow_jobs.stderr`\n    WHERE jsonPayload.type != \"presubmit\"\n        AND jsonPayload.job NOT LIKE \"%test_of_prowjob%\"\n        AND jsonPayload.to IN ( \"success\", \"error\", \"failure\")\n)\nSELECT \n    IFNULL(jobs_current.job, jobs_prev.job) as job,\n    IFNULL(jobs_current.cnt, 0) as cnt,\n    IFNULL(jobs_current.success, jobs_prev.success) as success,\n    IFNULL(jobs_current.success, jobs_prev.success) - IFNULL(jobs_prev.success, 0) as difference\nFROM\n(\n    SELECT \n    job,\n        COUNT(*) as `cnt`,\n        COUNTIF(state = \"success\") / COUNT(*) * 100 as `success`\n    FROM all_jobs\n    WHERE timestamp > $__millisTimeFrom(timestamp)\n    AND timestamp < $__millisTimeTo(timestamp)\n    GROUP BY job\n    ORDER BY job\n) as jobs_current\nFULL JOIN\n(\n    SELECT \n        job,\n        COUNT(*) as `cnt`,\n        COUNTIF(state = \"success\") / COUNT(*) * 100 as `success`\n    FROM all_jobs\n    WHERE timestamp > TIMESTAMP_SECONDS(UNIX_SECONDS($__millisTimeFrom(timestamp)) - (UNIX_SECONDS($__millisTimeTo(timestamp)) - UNIX_SECONDS($__millisTimeFrom(timestamp))))\n    AND timestamp < $__millisTimeFrom(timestamp)\n    GROUP BY job\n    ORDER BY job\n) as jobs_prev\nON jobs_current.job = jobs_prev.job\n"
    }
   ]
  },
  {
   "title": "Total incidents",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        number,\n        labels_unpacked.name as label\n    FROM sap-kyma-prow.github_issues.github_tools_sap_kyma, UNNEST(labels) as labels_unpacked\n    WHERE (closed_at IS NULL OR closed_at > $__millisTimeTo(closed_at) )\n    and created_at < $__millisTimeTo(closed_at)\n)\nSELECT \n    current_timestamp() as time,\n    label as metric,\n    COUNT(*)\nFROM issues_filtered\nWHERE label LIKE \"%incident\"\nAND number IN (SELECT number FROM issues_filtered  WHERE label = \"bug\")\nGROUP BY label\nORDER BY label"
    }
   ]
  },
  {
   "title": "Total bugs open",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    (\n        SELECT DISTINCT \n            repository.name as repository,\n            CONCAT(\"https://github.com/kyma-project/\", repository.name, \"/labels/bug\") as url,\n            number,\n            labels_unpacked.name as label,\n            created_at,\n            closed_at\n        FROM `sap-kyma-prow.github_issues.github_com_kyma_project`, UNNEST(labels) as labels_unpacked\n        WHERE labels_unpacked.name = \"bug\" AND repository.name IN (\"kyma\", \"control-plane\")\n    )\n    UNION ALL\n    (\n        SELECT DISTINCT\n            \"SKR\" as repository,\n            CONCAT(\"https://github.tools.sap/kyma/\", repository.name, \"/labels/bug\") as url,\n            number,\n            labels_unpacked.name as label,\n            created_at,\n            closed_at\n        FROM `sap-kyma-prow.github_issues.github_tools_sap_kyma`, UNNEST(labels) as labels_unpacked\n        WHERE labels_unpacked.name = \"bug\" AND repository.name = \"backlog\"\n    )\n)\nSELECT\n    IFNULL(bugs_open.repository, bugs_prev.repository) as repository,\n    IFNULL(bugs_open.url, bugs_prev.url) as url,\n    IFNULL(bugs_open.cnt, 0) as open,\n    IFNULL(bugs_open.cnt, 0) - IFNULL(bugs_prev.cnt, 0) as difference\nFROM\n(\n    SELECT \n        repository,\n        url,\n        COUNT(*) as `cnt`\n    FROM issues_filtered\n    WHERE (closed_at IS NULL OR closed_at > $__millisTimeTo(closed_at))\n    AND created_at < $__millisTimeTo(created_at)\n    GROUP BY repository, url\n    ORDER BY repository ASC\n) as bugs_open\nFULL JOIN\n(\n    SELECT \n        repository,\n        url,\n        COUNT(*) as `cnt`\n    FROM issues_filtered\n    WHERE (closed_at IS NULL OR closed_at > $__millisTimeFrom(closed_at))\n    AND created_at < $__millisTimeFrom(closed_at)\n    GROUP BY repository, url\n    ORDER BY repository ASC\n) as bugs_prev\nON bugs_open.repository = bugs_prev.repository\nORDER BY repository"
    }
   ]
  },
  {
   "title": "New incidents",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    SELECT DISTINCT \n        number,\n        labels_unpacked.name as label\n    FROM sap-kyma-prow.github_issues.github_tools_sap_kyma, UNNEST(labels) as labels_unpacked\n    WHERE created_at >= TIMESTAMP_SUB($__millisTimeTo(created_at), INTERVAL 7 DAY)\n    AND (closed_at IS NULL OR closed_at > $__millisTimeTo(closed_at) )\n    AND created_at > $__millisTimeFrom(closed_at)\n)\nSELECT \n    current_timestamp() as time,\n    label as metric,\n    COUNT(*)\nFROM issues_filtered\nWHERE label LIKE \"%incident\"\nAND number IN (SELECT number FROM issues_filtered  WHERE label = \"bug\")\nGROUP BY label\nORDER BY label"
    }
   ]
  },
  {
   "title": "Open bug age",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH bugs AS\n(\n  (\n    SELECT DISTINCT \n        repository.name as repository,\n        number,\n        labels_unpacked.name as label,\n        created_at,\n        closed_at\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`, UNNEST(labels) as labels_unpacked\n    WHERE repository.name  IN (\"kyma\", \"control-plane\") AND labels_unpacked.name = \"bug\"\n  )\n  UNION ALL\n  (\n    SELECT DISTINCT\n        repository.name as repository,\n        number,\n        labels_unpacked.name as label,\n        created_at,\n        closed_at\n    FROM `sap-kyma-prow.github_issues.github_tools_sap_kyma`, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"bug\"\n    AND repository.name = \"backlog\"\n  )\n)\n\nSELECT r.* FROM (\n    SELECT \n    [\n        STRUCT<age STRING, prev INT64, open INT64>\n            (\n                \"Up to 1 week\",\n                (\n                    SELECT \n                        COUNT(*)\n                    FROM bugs \n                    WHERE created_at > TIMESTAMP_SUB($__millisTimeFrom(created_at), INTERVAL 7 DAY) \n                    AND created_at < $__millisTimeFrom(created_at)\n                    AND (closed_at IS NULL OR closed_at > $__millisTimeFrom(created_at))\n                ),\n                (\n                    SELECT \n                        COUNT(*)\n                    FROM bugs \n                    WHERE created_at > TIMESTAMP_SUB($__millisTimeTo(created_at), INTERVAL 7 DAY)\n                    AND created_at < $__millisTimeTo(created_at)\n                    AND (closed_at IS NULL OR closed_at > $__millisTimeTo(created_at))\n                )\n            ),\n            (\n                \"Older than 1 month\",\n                (\n                    SELECT \n                        COUNT(*)\n                    FROM bugs \n                    WHERE created_at < TIMESTAMP(DATE_SUB(DATE($__millisTimeFrom(created_at)), INTERVAL 1 MONTH))\n                    AND (closed_at IS NULL OR closed_at > $__millisTimeFrom(created_at))\n                ),\n                (\n                    SELECT \n                        COUNT(*)\n                    FROM bugs \n                    WHERE created_at < TIMESTAMP(DATE_SUB(DATE($__millisTimeTo(created_at)), INTERVAL 1 MONTH))\n                    AND (closed_at IS NULL OR closed_at > $__millisTimeTo(created_at))\n                )\n            ),\n            (\n                \"Older than 3 months\",\n                (\n                    SELECT \n                        COUNT(*)\n                    FROM bugs \n                    WHERE created_at < TIMESTAMP(DATE_SUB(DATE($__millisTimeFrom(created_at)), INTERVAL 3 MONTH))\n                    AND (closed_at IS NULL OR closed_at > $__millisTimeFrom(created_at))\n                ),\n                (\n                    SELECT \n                        COUNT(*)\n                    FROM bugs \n                    WHERE created_at < TIMESTAMP(DATE_SUB(DATE($__millisTimeTo(created_at)), INTERVAL 3 MONTH))\n                    AND (closed_at IS NULL OR closed_at > $__millisTimeTo(created_at))\n                )\n            ),\n            (\n                \"Older than 6 months\",\n                (\n                    SELECT \n                        COUNT(*)\n                    FROM bugs \n                    WHERE created_at < TIMESTAMP(DATE_SUB(DATE($__millisTimeFrom(created_at)), INTERVAL 6 MONTH))\n                    AND (closed_at IS NULL OR closed_at > $__millisTimeFrom(created_at))\n                ),\n                (\n                    SELECT \n                        COUNT(*)\n                    FROM bugs \n                    WHERE created_at < TIMESTAMP(DATE_SUB(DATE($__millisTimeTo(created_at)), INTERVAL 6 MONTH))\n                    AND (closed_at IS NULL OR closed_at > $__millisTimeTo(created_at))\n                )\n            )\n    ] as row\n), UNNEST(row) as r\n"
    }
   ]
  },
  {
   "title": "Test coverage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH JOBS as (\nSELECT\n      MIN(CAST(REGEXP_EXTRACT(textPayload, r\"(\\d+\\.\\d+)\") AS float64)) AS val\n    , ANY_VALUE(labels.k8s_pod_prow_k8s_io_job) AS k8s_pod_prow_k8s_io_job\n    , MIN(timestamp) as timestamp\n  FROM `sap-kyma-prow.total_test_coverage.stdout`\n  GROUP BY resource.labels.pod_name\n  HAVING k8s_pod_prow_k8s_io_job NOT LIKE \"pre-%\"\n  AND k8s_pod_prow_k8s_io_job NOT LIKE \"rel-%\"\n  AND k8s_pod_prow_k8s_io_job NOT LIKE \"%-tests-%\"\n)\nSELECT a.k8s_pod_prow_k8s_io_job\n     , b.last_result\n     , b.last_timestamp\n     , a.samples_cnt\n     , a.min_result\n     , a.max_result\n     , ROUND(COALESCE((b.last_result - b.previous_result), 0),2) AS last_change\n     , format(\"https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/%s\", a.k8s_pod_prow_k8s_io_job)  as link\n     , a.stddev\n from \n( SELECT\n    k8s_pod_prow_k8s_io_job\n  , MIN(val) AS min_result\n  , MAX(val) AS max_result\n  , AVG(val) AS avg \n  , COUNT(*) AS samples_cnt\n  , MAX(timestamp) AS timestamp\n  , STDDEV_POP(val) AS stddev\nFROM JOBS\nGROUP BY k8s_pod_prow_k8s_io_job\nORDER BY k8s_pod_prow_k8s_io_job\n) a \nJOIN (SELECT \n   distinct(k8s_pod_prow_k8s_io_job) \n , FIRST_VALUE(val) OVER w1 AS last_result\n , FIRST_VALUE(timestamp) OVER w1 AS last_timestamp\n , NTH_VALUE(val,2) OVER w1 AS previous_result\nFROM JOBS\n WINDOW w1 AS (\n    PARTITION BY k8s_pod_prow_k8s_io_job ORDER BY timestamp DESC\n    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)\n) b on a.k8s_pod_prow_k8s_io_job = b.k8s_pod_prow_k8s_io_job"
    }
   ]
  },
  {
   "title": "Open bugs per area",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "2",
     "rawSql": "WITH issues_filtered AS\n(\n    (\n        SELECT DISTINCT \n            repository.name as repository,\n            number,\n            labels_unpacked.name as label,\n            created_at,\n            closed_at\n        FROM `sap-kyma-prow.github_issues.github_com_kyma_project`, UNNEST(labels) as labels_unpacked\n        WHERE repository.name IN (\"kyma\", \"control-plane\")\n    )\n    UNION ALL\n    (\n        SELECT DISTINCT\n            repository.name as repository,\n            number,\n            labels_unpacked.name as label,\n            created_at,\n            closed_at\n        FROM `sap-kyma-prow.github_issues.github_tools_sap_kyma`, UNNEST(labels) as labels_unpacked\n        WHERE repository.name = \"backlog\"\n    )\n)\nSELECT\n    IFNULL(issues_open.area, issues_prev.area) as area,\n    IFNULL(issues_open.cnt, 0) as open,\n    IFNULL(issues_open.cnt, 0) - IFNULL(issues_prev.cnt, 0) as difference,\nFROM\n(\n    SELECT \n        SUBSTR(label,6) as area,\n        COUNT(*) as `cnt`\n    FROM issues_filtered\n    WHERE label LIKE \"area/%\"\n    AND (number, repository) IN (SELECT (number, repository) FROM issues_filtered WHERE label = \"bug\")\n    AND (closed_at IS NULL OR closed_at > $__millisTimeTo(closed_at))\n    AND created_at < $__millisTimeTo(created_at)\n    GROUP BY label\n    ORDER BY area\n) as issues_open\nFULL JOIN\n(\n    SELECT \n      SUBSTR(label,6) as area,\n      COUNT(*) as `cnt`\n    FROM issues_filtered\n    WHERE label LIKE \"area/%\"\n    AND (number, repository) IN (SELECT (number, repository) FROM issues_filtered WHERE label = \"bug\")\n    -- get all issues that were created BEFORE the selected period, and still open or closed AFTER/DURING selected period\n    AND (closed_at IS NULL OR closed_at > $__millisTimeFrom(closed_at))\n    AND created_at < $__millisTimeFrom(closed_at)\n    GROUP BY label\n    ORDER BY area\n) as issues_prev\nON issues_open.area = issues_prev.area\n"
    }
   ]
  },
  {
   "title": "Test cases for release",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 17 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n  (\n    SELECT DISTINCT \n        repository.name as repository,\n        CONCAT(\"https://github.com/kyma-project/\", repository.name, \"/labels/test-case\") as url,\n        number,\n        labels_unpacked.name as label,\n            created_at,\n            closed_at\n    FROM `sap-kyma-prow.github_issues.github_com_kyma_project`, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"test-case\"\n  )\n  UNION ALL\n  (\n    SELECT DISTINCT\n        \"SKR\" as repository,\n        CONCAT(\"https://github.tools.sap/kyma/\", repository.name, \"/labels/test-case\") as url,\n        number,\n        labels_unpacked.name as label,\n            created_at,\n            closed_at\n    FROM `sap-kyma-prow.github_issues.github_tools_sap_kyma`, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"test-case\"\n    AND repository.name = \"backlog\"\n  )\n)\nSELECT \n    IFNULL(issues_open.repository, issues_prev.repository) as repository,\n    IFNULL(issues_open.url, issues_prev.url) as url,\n    IFNULL(issues_open.cnt, 0) as open,\n    IFNULL(issues_open.cnt, 0) - IFNULL(issues_prev.cnt, 0) as difference\nFROM \n(\n    SELECT \n        repository,\n        url,\n        COUNT(*) as `cnt`\n    FROM issues_filtered\n    WHERE created_at < $__millisTimeTo(created_at)\n    AND (closed_at IS NULL OR closed_at > $__millisTimeTo(closed_at) )\n    GROUP BY repository, url\n) as issues_open\nFULl JOIN\n(\n    SELECT \n        repository,\n        url,\n        COUNT(*) as `cnt`\n    FROM issues_filtered\n    WHERE created_at < $__millisTimeFrom(created_at)\n    AND (closed_at IS NULL OR closed_at > $__millisTimeFrom(closed_at) )\n    GROUP BY repository, url\n) as issues_prev\nON issues_open.repository = issues_prev.repository\n--GROUP BY issues_open.repository, issues_open.url\nORDER BY issues_open.repository"
    }
   ]
  },
  {
   "title": "Critical issues",
   "type": "table-old",
   "description": "New counts all opened in the last 7 days",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 22 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH issues_filtered AS\n(\n    (\n    SELECT DISTINCT \n        repository.name as repository,\n        CONCAT(\"https://github.com/kyma-project/\", repository.name, \"/labels/priority/critical\") as url,\n        number,\n        labels_unpacked.name as label,\n        created_at,\n        closed_at\n    FROM sap-kyma-prow.github_issues.github_com_kyma_project, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"priority/critical\"\n    )\n    UNION ALL \n    ( \n        SELECT DISTINCT \n        \"SKR\" as repository,\n        CONCAT(\"https://github.tools.sap/kyma/\", repository.name, \"/labels/priority/critical\") as url,\n        number,\n        labels_unpacked.name as label,\n        created_at,\n        closed_at\n    FROM sap-kyma-prow.github_issues.github_tools_sap_kyma, UNNEST(labels) as labels_unpacked\n    WHERE labels_unpacked.name = \"priority/critical\"\n    AND repository.name = \"backlog\"\n    )\n)\nSELECT\n    issues_all.repository,\n    issues_all.url,\n    critical_open,\n    COALESCE(critical_new, 0),\n    critical_open -COALESCE(critical_open_prev,0) as difference\nFROM\n(\n    SELECT \n        repository,\n        url,\n        COUNT(*) as `critical_open`\n    FROM issues_filtered\n    WHERE (closed_at IS NULL OR closed_at > $__millisTimeTo(closed_at) )\n    GROUP BY repository, url\n) AS issues_all LEFT JOIN (\n    SELECT \n        repository,\n        url,\n        COUNT(*) as `critical_new`\n    FROM issues_filtered\n    WHERE created_at > $__millisTimeFrom(created_at)\n    AND created_at < $__millisTimeTo(created_at)\n    AND (closed_at IS NULL OR closed_at > $__millisTimeTo(closed_at) )\n    GROUP BY repository, url\n) AS issues_new\nON issues_all.repository = issues_new.repository\nLEFT JOIN (\n    SELECT \n        repository,\n        url,\n        COUNT(*) as `critical_open_prev`\n    FROM issues_filtered\n    WHERE (closed_at IS NULL OR closed_at > $__millisTimeFrom(closed_at) )\n    GROUP BY repository, url\n) as issues_prev\nON issues_all.repository = issues_prev.repository\nORDER BY repository"
    }
   ]
  }
 ]
}