{
 "title": "quality dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "all-jobs",
   "type": "table",
   "gridPos": { "h": 40, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "WITH JOBS as (\nSELECT\n      MIN(CAST(REGEXP_EXTRACT(textPayload, r\"(\\d+\\.\\d+)\") AS float64)) AS val\n    , ANY_VALUE(labels.k8s_pod_prow_k8s_io_job) AS k8s_pod_prow_k8s_io_job\n    , MIN(timestamp) as timestamp\n  FROM `sap-kyma-prow.total_test_coverage.stdout`\n  GROUP BY resource.labels.pod_name\n  HAVING k8s_pod_prow_k8s_io_job NOT LIKE \"pre-%\"\n)\nSELECT a.k8s_pod_prow_k8s_io_job\n     , b.last_result\n     , b.last_timestamp\n     , a.samples_cnt\n     , a.min_result\n     , a.max_result\n     , ROUND(COALESCE((b.last_result - b.previous_result), 0),2) AS last_change\n     , format(\"https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/%s\", a.k8s_pod_prow_k8s_io_job)  as link\n     , a.stddev\n from \n( SELECT\n    k8s_pod_prow_k8s_io_job\n  , MIN(val) AS min_result\n  , MAX(val) AS max_result\n  , AVG(val) AS avg \n  , COUNT(*) AS samples_cnt\n  , MAX(timestamp) AS timestamp\n  , STDDEV_POP(val) AS stddev\nFROM JOBS\nGROUP BY k8s_pod_prow_k8s_io_job\nORDER BY k8s_pod_prow_k8s_io_job\n) a \nJOIN (SELECT \n   distinct(k8s_pod_prow_k8s_io_job) \n , FIRST_VALUE(val) OVER w1 AS last_result\n , FIRST_VALUE(timestamp) OVER w1 AS last_timestamp\n , NTH_VALUE(val,2) OVER w1 AS previous_result\nFROM JOBS\n WINDOW w1 AS (\n    PARTITION BY k8s_pod_prow_k8s_io_job ORDER BY timestamp DESC\n    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)\n) b on a.k8s_pod_prow_k8s_io_job = b.k8s_pod_prow_k8s_io_job"
    }
   ]
  },
  {
   "title": "single-job",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n    MIN(CAST(REGEXP_EXTRACT(textPayload, r\"(\\d+\\.\\d+)\") as float64)) as result\n  , labels.k8s_pod_prow_k8s_io_job as metric\n  , max(timestamp) as timestamp\nFROM `sap-kyma-prow.total_test_coverage.stdout`\nWHERE $__timeFilter(timestamp)\nGROUP BY resource.labels.pod_name, labels.k8s_pod_prow_k8s_io_job\n--HAVING labels.k8s_pod_prow_k8s_io_job = \"pre-rafter\"\nHAVING labels.k8s_pod_prow_k8s_io_job not like \"pre-%\"\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "last-and-previous result",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n     distinct k8s_pod_prow_k8s_io_job\n   , FIRST_VALUE(val)\n       OVER w1 AS last_result\n   , NTH_VALUE(val,2)\n       OVER w1 AS previous_result\n   , FIRST_VALUE(timestamp)\n       OVER w1 AS last_timestamp\n   , NTH_VALUE(timestamp,2)\n       OVER w1 AS previous_timestamp\n   , format(\"https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/%s\", k8s_pod_prow_k8s_io_job)  as link\nFROM \n--`sap-kyma-prow.total_test_coverage.stdout`\n(\n  SELECT\n      MIN(CAST(REGEXP_EXTRACT(textPayload, r\"(\\d{1,2})\") as int64)) as val\n    , labels.k8s_pod_prow_k8s_io_job as k8s_pod_prow_k8s_io_job\n    , MAX(timestamp) as timestamp\n  FROM `sap-kyma-prow.total_test_coverage.stdout`\n  WHERE $__timeFilter(timestamp)\n  GROUP BY resource.labels.pod_name, labels.k8s_pod_prow_k8s_io_job\n) main\nwhere k8s_pod_prow_k8s_io_job not like 'pre%'\n--and k8s_pod_prow_k8s_io_job = \"post-master-hydroform\"\n  WINDOW w1 AS (\n    PARTITION BY k8s_pod_prow_k8s_io_job ORDER BY timestamp DESC\n    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)\norder by 2 desc"
    }
   ]
  }
 ]
}