// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	mock "github.com/stretchr/testify/mock"
	compute "google.golang.org/api/compute/v1"
)

// InstancesAPI is an autogenerated mock type for the InstancesAPI type
type InstancesAPI struct {
	mock.Mock
}

// ListInstances provides a mock function with given fields: project
func (_m *InstancesAPI) ListInstances(project string) ([]*compute.Instance, error) {
	ret := _m.Called(project)

	var r0 []*compute.Instance
	if rf, ok := ret.Get(0).(func(string) []*compute.Instance); ok {
		r0 = rf(project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*compute.Instance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveInstance provides a mock function with given fields: project, zone, name
func (_m *InstancesAPI) RemoveInstance(project string, zone string, name string) error {
	ret := _m.Called(project, zone, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(project, zone, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
