// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	context "context"

	cluster "github.com/kyma-project/test-infra/development/prow-installer/pkg/cluster"

	mock "github.com/stretchr/testify/mock"
)

// API is an autogenerated mock type for the API type
type API struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, clusterConfig
func (_m *API) Create(ctx context.Context, clusterConfig cluster.Cluster) error {
	ret := _m.Called(ctx, clusterConfig)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, cluster.Cluster) error); ok {
		r0 = rf(ctx, clusterConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, name, zoneID
func (_m *API) Delete(ctx context.Context, name string, zoneID string) error {
	ret := _m.Called(ctx, name, zoneID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, zoneID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
