// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// ComputeAPI is an autogenerated mock type for the ComputeAPI type
type ComputeAPI struct {
	mock.Mock
}

// RemoveIP provides a mock function with given fields: project, region, name
func (_m *ComputeAPI) RemoveIP(project string, region string, name string) (bool, error) {
	ret := _m.Called(project, region, name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(project, region, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(project, region, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
