// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	event "github.com/cloudevents/sdk-go/v2/event"
	apperrors "github.com/kyma-project/test-infra/development/kyma-github-connector/githubWebhookGateway/pkg/apperrors"

	mock "github.com/stretchr/testify/mock"
)

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: payload
func (_m *Validator) Validate(payload event.Event) apperrors.AppError {
	ret := _m.Called(payload)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(event.Event) apperrors.AppError); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}
