log-format: json
default-merge-group-tag:
  name: default_tag
  value: "0.0.0-MG.{{ .ShortSHA }}"
  validation: "^0\\.0\\.0-MG\\.[0-9a-f]{8}$"
default-pr-tag:
  name: default_tag
  value: "v{{ .PRNumber }}-PR"
  validation: "^v[0-9]+-PR$"
ado-config:
  ado-organization-url: https://dev.azure.com/hyperspace-pipelines
  ado-project-name: kyma
  ado-pipeline-id: 14902
  ado-retry-strategy:
    attempts: 3
    delay: 5s
  ado-refresh-interval: 15s
