// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	compute "google.golang.org/api/compute/v1"

	mock "github.com/stretchr/testify/mock"
)

// DiskAPI is an autogenerated mock type for the DiskAPI type
type DiskAPI struct {
	mock.Mock
}

// ListDisks provides a mock function with given fields: project, zone
func (_m *DiskAPI) ListDisks(project string, zone string) ([]*compute.Disk, error) {
	ret := _m.Called(project, zone)

	var r0 []*compute.Disk
	if rf, ok := ret.Get(0).(func(string, string) []*compute.Disk); ok {
		r0 = rf(project, zone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*compute.Disk)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(project, zone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveDisk provides a mock function with given fields: name, project, zone
func (_m *DiskAPI) RemoveDisk(name string, project string, zone string) error {
	ret := _m.Called(name, project, zone)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, project, zone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
