{
 "title": "Prow",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Success rate (24H)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prowjobs{state=\"success\"} or prowjobs * 0) / (sum(prowjobs{state=\"failure\"} or prowjobs * 0) + sum(prowjobs{state=\"success\"} or prowjobs * 0))"
    }
   ]
  },
  {
   "title": "Postsubmit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prowjobs{state=\"success\", type=\"postsubmit\"} or prowjobs * 0) / (sum(prowjobs{state=\"failure\", type=\"postsubmit\"} or prowjobs * 0) + sum(prowjobs{state=\"success\", type=\"postsubmit\"} or prowjobs * 0))"
    }
   ]
  },
  {
   "title": "Presubmit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prowjobs{state=\"success\", type=\"presubmit\"} or prowjobs * 0) / (sum(prowjobs{state=\"failure\", type=\"presubmit\"} or prowjobs * 0) + sum(prowjobs{state=\"success\", type=\"presubmit\"} or prowjobs * 0))"
    }
   ]
  },
  {
   "title": "Periodic",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prowjobs{state=\"success\", type=\"periodic\"} or prowjobs * 0) / (sum(prowjobs{state=\"failure\", type=\"periodic\"} or prowjobs * 0) + sum(prowjobs{state=\"success\", type=\"periodic\"} or prowjobs * 0))"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prowjobs{state=\"triggered\"})",
     "legendFormat": "Queued"
    },
    {
     "expr": "sum(prowjobs{state=\"pending\"})",
     "legendFormat": "In progress"
    }
   ]
  }
 ]
}