// Code generated by mockery 2.9.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// RepoAPI is an autogenerated mock type for the RepoAPI type
type RepoAPI struct {
	mock.Mock
}

// ListSubrepositories provides a mock function with given fields: repoName
func (_m *RepoAPI) ListSubrepositories(repoName string) ([]string, error) {
	ret := _m.Called(repoName)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(repoName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(repoName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
