// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	iam "google.golang.org/api/iam/v1"
)

// IAM is an autogenerated mock type for the IAM type
type IAM struct {
	mock.Mock
}

// CreateSA provides a mock function with given fields: request, projectname
func (_m *IAM) CreateSA(request *iam.CreateServiceAccountRequest, projectname string) (*iam.ServiceAccount, error) {
	ret := _m.Called(request, projectname)

	var r0 *iam.ServiceAccount
	if rf, ok := ret.Get(0).(func(*iam.CreateServiceAccountRequest, string) *iam.ServiceAccount); ok {
		r0 = rf(request, projectname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iam.ServiceAccount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*iam.CreateServiceAccountRequest, string) error); ok {
		r1 = rf(request, projectname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
