// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import client "github.com/kyma-project/test-infra/development/tools/pkg/gcscleaner/client"
import mock "github.com/stretchr/testify/mock"

// BucketIterator is an autogenerated mock type for the BucketIterator type
type BucketIterator struct {
	mock.Mock
}

// Next provides a mock function with given fields:
func (_m *BucketIterator) Next() (client.BucketAttrs, error) {
	ret := _m.Called()

	var r0 client.BucketAttrs
	if rf, ok := ret.Get(0).(func() client.BucketAttrs); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.BucketAttrs)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
