// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import compute "google.golang.org/api/compute/v1"
import mock "github.com/stretchr/testify/mock"

// ComputeAPI is an autogenerated mock type for the ComputeAPI type
type ComputeAPI struct {
	mock.Mock
}

// checkInstance provides a mock function with given fields: project, zone, name
func (_m *ComputeAPI) checkInstance(project string, zone string, name string) bool {
	ret := _m.Called(project, zone, name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(project, zone, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// deleteBackendService provides a mock function with given fields: project, backendService
func (_m *ComputeAPI) deleteBackendService(project string, backendService string) {
	_m.Called(project, backendService)
}

// deleteForwardingRule provides a mock function with given fields: project, name, region
func (_m *ComputeAPI) deleteForwardingRule(project string, name string, region string) {
	_m.Called(project, name, region)
}

// deleteGlobalForwardingRule provides a mock function with given fields: project, name
func (_m *ComputeAPI) deleteGlobalForwardingRule(project string, name string) {
	_m.Called(project, name)
}

// deleteHTTPProxy provides a mock function with given fields: project, httpProxy
func (_m *ComputeAPI) deleteHTTPProxy(project string, httpProxy string) {
	_m.Called(project, httpProxy)
}

// deleteHealthChecks provides a mock function with given fields: project, names
func (_m *ComputeAPI) deleteHealthChecks(project string, names []string) {
	_m.Called(project, names)
}

// deleteInstanceGroup provides a mock function with given fields: project, zone, instanceGroup
func (_m *ComputeAPI) deleteInstanceGroup(project string, zone string, instanceGroup string) {
	_m.Called(project, zone, instanceGroup)
}

// deleteTargetPool provides a mock function with given fields: project, name, region
func (_m *ComputeAPI) deleteTargetPool(project string, name string, region string) {
	_m.Called(project, name, region)
}

// deleteURLMap provides a mock function with given fields: project, urlMap
func (_m *ComputeAPI) deleteURLMap(project string, urlMap string) {
	_m.Called(project, urlMap)
}

// lookupBackendServices provides a mock function with given fields: project
func (_m *ComputeAPI) lookupBackendServices(project string) ([]*compute.BackendService, error) {
	ret := _m.Called(project)

	var r0 []*compute.BackendService
	if rf, ok := ret.Get(0).(func(string) []*compute.BackendService); ok {
		r0 = rf(project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*compute.BackendService)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// lookupGlobalForwardingRule provides a mock function with given fields: project
func (_m *ComputeAPI) lookupGlobalForwardingRule(project string) ([]*compute.ForwardingRule, error) {
	ret := _m.Called(project)

	var r0 []*compute.ForwardingRule
	if rf, ok := ret.Get(0).(func(string) []*compute.ForwardingRule); ok {
		r0 = rf(project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*compute.ForwardingRule)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// lookupHTTPProxy provides a mock function with given fields: project
func (_m *ComputeAPI) lookupHTTPProxy(project string) ([]*compute.TargetHttpProxy, error) {
	ret := _m.Called(project)

	var r0 []*compute.TargetHttpProxy
	if rf, ok := ret.Get(0).(func(string) []*compute.TargetHttpProxy); ok {
		r0 = rf(project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*compute.TargetHttpProxy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// lookupInstanceGroup provides a mock function with given fields: project, zone
func (_m *ComputeAPI) lookupInstanceGroup(project string, zone string) ([]string, error) {
	ret := _m.Called(project, zone)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string, string) []string); ok {
		r0 = rf(project, zone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(project, zone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// lookupTargetPools provides a mock function with given fields: project
func (_m *ComputeAPI) lookupTargetPools(project string) ([]*compute.TargetPool, error) {
	ret := _m.Called(project)

	var r0 []*compute.TargetPool
	if rf, ok := ret.Get(0).(func(string) []*compute.TargetPool); ok {
		r0 = rf(project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*compute.TargetPool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// lookupURLMaps provides a mock function with given fields: project
func (_m *ComputeAPI) lookupURLMaps(project string) ([]*compute.UrlMap, error) {
	ret := _m.Called(project)

	var r0 []*compute.UrlMap
	if rf, ok := ret.Get(0).(func(string) []*compute.UrlMap); ok {
		r0 = rf(project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*compute.UrlMap)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// lookupZones provides a mock function with given fields: project, pattern
func (_m *ComputeAPI) lookupZones(project string, pattern string) ([]string, error) {
	ret := _m.Called(project, pattern)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string, string) []string); ok {
		r0 = rf(project, pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(project, pattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
