name: all-checks-passed
on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        edited,
        labeled,
      ]
  merge_group:
   

jobs:
  all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@204ff63e89eabdc8086f0c50b91f675bcf37c8f6 # v2.4.0
        with:
          delay: '3'
          retries: '30'
          polling_interval: '1'