name: build-image-builder.yml
# description: "Build image-builder image for image-builder application."
on:
  # This workflow is triggered by workflow controller.
  workflow_call:

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  generate-timestamp-tag:
    uses: kyma-project/test-infra/.github/workflows/reusable-generate-timestamp-tag.yml@dbefa5f119885ba93fe619ba03268d78435bb957 # main

  build-image:
    needs: generate-timestamp-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@dbefa5f119885ba93fe619ba03268d78435bb957 # main
    with:
      name: image-builder
      dockerfile: cmd/image-builder/Dockerfile
      context: .
      platforms: |
        linux/amd64
      tags: |
        ${{ needs.generate-timestamp-tag.outputs.tag }}