name: pull-validate-dockerfiles

on:
  # This workflow is triggered by workflow controller.
  workflow_call:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: kyma-project/test-infra/.github/actions/checkout@main

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@2a66e89f53d0771bb131a7fa31f3136336094aa6 # v3.4.0
        with:
          dockerfile: "Dockerfile"
          recursive: true
