name: workflow-controller-build-2

on:
  pull_request_target: 
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
  merge_group: 

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  detect-changed-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.pathFilters.outputs.changes }}
    environment:
      name: prod
      deployment: false
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          repository: kyma-project/test-infra
          ref: main
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: pathFilters
        with:
          filters: .github/controller-filters.yaml

  build-rotate-service-account-keys:
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-rotate-service-account-keys-filter') }}
    needs: detect-changed-files
    uses: kyma-project/test-infra/.github/workflows/build-rotate-service-account-keys.yml@main
  
  build-service-account-keys-cleaner-filter:
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-service-account-keys-cleaner-filter') }}
    needs: detect-changed-files
    uses: kyma-project/test-infra/.github/workflows/build-service-account-keys-cleaner.yml@main

  build-signify-secret-rotator:
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-signify-secret-rotator-filter') }}
    needs: detect-changed-files
    uses: kyma-project/test-infra/.github/workflows/build-signify-secret-rotator.yml@main

  build-slack-message-sender:
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-slack-message-sender-filter') }}
    needs: detect-changed-files
    uses: kyma-project/test-infra/.github/workflows/build-slack-message-sender.yml@main
 
  build-oidc-token-verifier:
    needs: detect-changed-files
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-oidc-token-verifier-filter') }}
    uses: kyma-project/test-infra/.github/workflows/build-oidc-token-verifier.yml@main
